version: "3.8"

services:
  mongodb-appointments:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb-appointments
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    networks:
      - backend-appointments
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-appointments:/data/db

  appointment:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appointment
    environment:
      - MONGODB_URL=${MONGOURL}
      - PORT=3012
    depends_on:
      - mongodb-appointments
    networks:
      - backend-appointments
    ports:
      - "3012:3012"
    volumes:
      - .:/appointment-svc

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
    networks:
      - backend-appointments
      - rabbit-network
    ports:
      - "5672:5672"

volumes:
  mongo-data-appointments:

networks:
  backend-appointments:
    driver: bridge
  rabbit-network:
    external: true
