version: "3.8"

services:
  mongodb:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  appointment:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appointment
    environment:
      - MONGODB_URL=${MONGOURL}
      - PORT=3012
    depends_on:
      - mongodb
    networks:
      - backend
    ports:
      - "3012:3012"
    volumes:
      - .:/appointment-svc

  workshift:
    restart: unless-stopped
    image: cloudmedix/workshift
    container_name: workshift
    environment:
      - MONGODB_URL=${MONGOURL_WORKSHIFT}
      - PORT=3011
    depends_on:
      - mongodb
    networks:
      - backend
    ports:
      - "3011:3011"
    volumes:
      - .env:/workshift-svc/.env

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
    networks:
      - backend
    ports:
      - "5672:5672"

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
